- name: ":bug: bug"
  color: "F9D0C4"
  description: "Something isn't working"

- name: ":notebook: documentation"
  color: "F0F0F0"
  description: "Improvements or additions to documentation"

- name: ":sparkles: enhancement"
  description: "New feature or request"
  color: "F0F0F0"
  
- name: ":beginner: good first issue"
  description: "Good for newcomers"
  color: "F0F0F0"

- name: ":question: question"
  description: "Further information is requested"
  color: "F0F0F0"

- name: ":ice_cube: icebox"
  description: "icebox or pending"
  color: "F0F0F0"

- name: ":rocket: priority::high"
  description: "priority high"
  color: "F9D0C4"

- name: ":car: priority::low"
  description: "priority low"
  color: "C2E0C6"

- name: ":airplane: priority::medium"
  description: "priority medium"
  color: "FEF2C0"

- name: ":whale: major update"
  color: "F9D0C4"
  description: "Major update"

- name: ":dolphin: minor update"
  color: "FEF2C0"
  description: "Minor update"

- name: ":fish: patch"
  color: "C2E0C6"
  description: "Patch Update"

- name: ":wrench: tools"
  description: "Tools"
  color: "F0F0F0"

- name: ":artificial_satellite: C2A"
  description: "Command Centric Architecture"
  color: "F0F0F0"

- name: ":ringed_planet: S2E"
  description: "Spacecraft Simulation Environment"
  color: "F0F0F0"

- name: ":satellite: WINGS"
  description: "Web-based INterface Ground-station Software"
  color: "F0F0F0"
